hero:
  name: 安琪拉
  word: 火焰是我最喜欢的玩具
  Hp: 445.5

hero_name:
  - 安琪拉
  - 黄忠
  - 小乔

heros:
  - name: 黄忠
    word: 周日被我射熄火了
    Hp: 440

hero_name_list:
  - - 安琪拉
    - 黄忠
    - 小乔

hero_name_word:
  -
    - 黄忠
    - 周日被我射熄火了
  -
    - 安琪拉
    - 火焰是我最喜欢的玩具


#mobile_params:
## shouji,appkey
#  - - shouji: 13456755448
#    - appkey: 0c818521d38759e1
#mobile_params:
#  # shouji,appkey
#  - [13456755448,0c818521d38759e1]
##  - ["13456755400","0c818521d38759e1"]
mobile_params:
# shouji,appkey
  - - 13456755448
    - 0c818521d38759e1